name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-sha-tag:
    runs-on: ubuntu-latest
    outputs:
      sha-tag: ${{ steps.sha-tag.outputs.sha-tag }}
    steps:
      - name: Create short SHA to be used as a container tag
        id: sha-tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "sha-tag=$tag" >> $GITHUB_OUTPUT

  lint:
    uses: ./.github/workflows/linting.yml

  build-deploy:
    uses: ./.github/workflows/build.yml
    needs:
      - lint
      - generate-sha-tag
    with:
      sha-tag: ${{ needs.generate-sha-tag.outputs.sha-tag }}
    secrets: inherit
